repos:
  - repo: https://github.com/psf/black
    rev: "24.3.0"
    hooks:
      - id: black
        files: ^backend/
        args: ["--config", "backend/pyproject.toml"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.5.0"
    hooks:
      - id: ruff
        files: ^backend/
        args: ["--config", "backend/pyproject.toml"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.10.0"
    hooks:
      - id: mypy
        files: ^backend/
        args: ["--config-file", "backend/mypy.ini"]

  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.9"
    hooks:
      - id: bandit
        files: ^backend/
        args:
          - "-c"
          - "backend/pyproject.toml"
          - "-r"
          - "backend/app"
